version: '3'

services:
  trino:
    hostname: trino
    image: 'trinodb/trino:438'
    ports:
      - '8080:8080'
    # environment:
    #   - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      # - ./etc:/usr/lib/trino/etc:ro
      # - ./etc/catalog:/etc/trino/catalog 
      - $PWD/etc/catalog:/etc/trino/catalog 
      - ./sa-gcs-key.json:/sa-gcs-key.json
      # - ./etc/keys:/etc/trino/keys
      # - ./keys:/etc/trino/keys
    networks:
      - trino-network

  hive-metastore-standalone:
  # Based on https://hive.apache.org/developement/quickstart/
    # container_name: metastore-standalone 
    # image: apache/hive:3.1.3
    build: "./hive-metastore"
    ports:
      - "9083:9083"
    environment:
      - SERVICE_NAME=metastore
      # - DB_DRIVER=postgres
      # - SERVICE_OPTS="-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password"
      # - DATABASE_HOST=postgres
      # - DATABASE_DB=${POSTGRES_DB}
      # - DATABASE_USER=${POSTGRES_USER}
      # - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=metastore_db      
      - POSTGRES_USER=hive      
      - POSTGRES_PASSWORD=password
    volumes:
      # - ./hive-metastore/conf/metastore-site.xml:/opt/conf/metastore-site.xml
      # - ./hive-metastore/conf/core-site.xml:/opt/hive/conf/core-site.xml 
      # https://github.com/naushadh/hive-metastore/blob/main/run.sh
      - ./hive-metastore/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./sa-gcs-key.json:/sa-gcs-key.json

    # volumes:
    #   - warehouse:/opt/hive/data/warehouse
    #   # - /path/to/postgresql-42.5.1.jar:/opt/hive/lib/postgres.jar
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - trino-network

  # postgres:
  #   image: postgres:14-alpine
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - POSTGRES_DB=metastore_db      
  #     - POSTGRES_USER=hive      
  #     - POSTGRES_PASSWORD=password
  #     # - DATABASE_DB=${POSTGRES_DB}
  #     # - DATABASE_USER=${POSTGRES_USER}
  #     # - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "${POSTGRES_DB}"]
  #   networks:
  #     - trino-network

networks:
  trino-network:
    driver: bridge

# volumes:
#   warehouse:
