version: '3'

services:
  trino:
    container_name: trino
    image: 'trinodb/trino:439'
    ports:
      - '8080:8080'
    volumes:
      - $PWD/trino/etc/catalog:/etc/trino/catalog 
      - ./sa-gcs-key.json:/sa-gcs-key.json

  hive-metastore:
  # Based on https://hive.apache.org/developement/quickstart/
    # container_name: metastore-standalone 
    # image: apache/hive:3.1.3
    container_name: hive-metastore
    build: "./hive-metastore"
    ports:
      - "9083:9083"
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - DATABASE_HOST=postgres
      - DATABASE_DB=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=testSecret
      - LOCALSTACK_PORT={LOCALSTACK_PORT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=${S3_PREFIX}
      - S3_ENDPOINT_URL=http://localstack:${LOCALSTACK_PORT}
      - GCS_SA_PRIVATE_KEY_ID=${GCS_SA_PRIVATE_KEY_ID}
      - GCS_SA_EMAIL=${GCS_SA_EMAIL}
      - GCS_PROJECT_ID=${GCS_PROJECT_ID}
      - GCS_SA_PRIVATE_KEY=${GCS_SA_PRIVATE_KEY}

    volumes:
      # - ./hive-metastore/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./.env:/.env
      - ./sa-gcs-key.json:/sa-gcs-key.json


  postgres:
    image: postgres:14-alpine
    # environment:
      # - DATABASE_HOST=postgres
      # - DATABASE_DB=${POSTGRES_DB}
      # - DATABASE_USER=${POSTGRES_USER}
      # - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "${POSTGRES_DB}"]


# networks:
#   trino-network:
#     driver: bridge

