# Based on https://github.com/njanakiev/trino-minio-docker &
#   https://github.com/bitsondatadev/hive-metastore &
#   https://github.com/sairamkrish/trino-superset-demo  

services:
  trino:
    container_name: trino
    image: 'trinodb/trino:444'
    ports:
      - '8080:8080'
    volumes:
      - $PWD/trino/etc/catalog:/etc/trino/catalog 
      - ./lk-sa-gcs-key.json:/lk-sa-gcs-key.json
      - ./te-sa-gcs-key.json:/te-sa-gcs-key.json
    networks:
      - trino-network

  # HMS backend database
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.8
    # image: mariadb:11.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  # Hive metastore service (HMS) (using just one hive metastore service)
  hive-metastore:
    container_name: hive-metastore
    # image: 'bitsondatadev/hive-metastore:latest'
    build: './hive-metastore'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
      - ./hive-metastore/conf/core-site-te.xml:/opt/hadoop-3.2.0/etc/hadoop/core-site-te.xml
      - ./hive-metastore/conf/core-site-lk.xml:/opt/hadoop-3.2.0/etc/hadoop/core-site-lk.xml    
      - ./lk-sa-gcs-key.json:/opt/lk-sa-gcs-key.json
      - ./te-sa-gcs-key.json:/opt/te-sa-gcs-key.json
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - trino-network

  superset:
    container_name: superset
    # image: 'apache/superset:3.1.1'
    build: ./superset
    ports:
      - '8088:8088'
    environment:
      - TALISMAN_ENABLED=False
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    networks:
      - trino-network


  # te-hive-metastore:
  # # metastore for trino exemplar project
  #   container_name: te-hive-metastore
  #   build: './te-hive-metastore'
  #   ports:
  #     - '9083:9083' 
  #   volumes:
  #     - ./te-hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
  #     - ./te-hive-metastore/conf/core-site.xml:/opt/hadoop-3.2.0/etc/hadoop/core-site.xml
  #     - ./te-sa-gcs-key.json:/opt/te-sa-gcs-key.json
  #   environment:
  #     METASTORE_DB_HOSTNAME: mariadb
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - trino-network

  # lk-hive-metastore:
  # # metastore for my GCP project
  #   container_name: lk-hive-metastore
  #   build: './lk-hive-metastore'
  #   ports:
  #     - '9099:9083' 
  #   volumes:
  #     - ./lk-hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
  #     - ./lk-hive-metastore/conf/core-site.xml:/opt/hadoop-3.2.0/etc/hadoop/core-site.xml
  #     - ./lk-sa-gcs-key.json:/opt/lk-sa-gcs-key.json
  #   environment:
  #     METASTORE_DB_HOSTNAME: mariadb
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - trino-network

networks:
  trino-network:
    driver: bridge
